name: colt
version: 0.1.0
description: Vector and matrix algebra package
dependencies:
  intl: any
  complex: any
  quiver: any
dev_dependencies:
  test: any
  benchmark_harness: ">=1.0.0 <2.0.0"
  browser: any
